/**
 * Pick worked examples for the relevance prompt from the expert's own decisions.
 *
 * Decisions, not explanations. Rebuilding the rubric from his written reasons was measured
 * and lost to the rubric inferred from his verdicts: what someone says their rule is and what
 * their decisions encode are not the same thing. So these examples carry a description and a
 * verdict, and no rationale.
 *
 * TUNING SPLIT ONLY -- and "tuning split" means by CONTENT, not by identifier.
 *
 * The same scheme appears in this data under several authority names with different provider
 * ids: one application shows up as Cambridge, Greater Cambridge and South Cambridgeshire. A
 * hash split on the id therefore scatters copies of one scheme across both sides. An earlier
 * version of this script split on the id alone and emitted an example whose description is
 * word-for-word a held-out record, which puts a test answer straight into the prompt. So a
 * candidate is rejected when its description matches ANY held-out record, not merely when its
 * own id falls in the held-out third.
 *
 * Balanced on purpose: examples only from records the model gets wrong would teach it that
 * its instinct is always inverted. Half reinforce what it already does, half correct it.
 *
 * Run from apps/web:  npx tsx scripts/build-relevance-examples.ts
 */
import { loadEnvConfig } from '@next/env'
import { createClient } from '@supabase/supabase-js'
import { createHash } from 'crypto'
import { readFileSync } from 'fs'

loadEnvConfig(process.cwd())
const isHoldout = (id: string) =>
  createHash('sha256').update(`holdout:${id}`).digest().readUInt32BE(0) / 0xffffffff < 1 / 3

/** Descriptions differ only in whitespace and case between copies of the same scheme. */
const canonical = (description: string) => description.replace(/\s+/g, ' ').trim().toLowerCase()

async function main() {
  const args = process.argv.slice(2)
  const verifyOnly = args.includes('--verify')
  const cachePath = args.find((a) => !a.startsWith('--')) ?? 'runs/fl-ops.json'
  const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, {
    auth: { autoRefreshToken: false, persistSession: false },
  })
  const { data: apps } = await db.from('planning_applications')
    .select('provider_id,raw').eq('intelligence_tier', true).order('provider_id')
  const { data: lab } = await db.from('planning_label_submissions')
    .select('record_id,relevance,submitted_at').eq('labeller', 'rob').order('submitted_at')
  const rob = new Map<string, string>()
  for (const l of lab ?? []) rob.set(String(l.record_id), String(l.relevance))
  const cache = JSON.parse(readFileSync(cachePath, 'utf8'))

  // Every description on the held-out side, whatever id carries it. Anything matching one of
  // these is unusable as an example even if its own id sits in the tuning third.
  const heldOutText = new Set<string>()
  for (const a of apps ?? []) {
    if (!isHoldout(a.provider_id as string)) continue
    const d = String((a.raw as { description?: string }).description ?? '')
    if (d.trim()) heldOutText.add(canonical(d))
  }

  if (verifyOnly) {
    const src = readFileSync('src/lib/planning-intelligence/openrouter.ts', 'utf8')
    const block = src.slice(src.indexOf('const RELEVANCE_EXAMPLES'), src.indexOf("].join(' | ')"))
    const inPrompt = [...block.matchAll(/'(.+?) -> (?:high|medium|low)'/g)]
      .map((m) => canonical(m[1].replace(/\\'/g, "'")))
    const bad = inPrompt.filter((d) => heldOutText.has(d))
    console.log(`${inPrompt.length} example(s) in the prompt; ${bad.length} match a held-out record`)
    for (const d of bad) console.log(`  LEAKED: ${d.slice(0, 90)}`)
    process.exit(bad.length === 0 ? 0 : 1)
  }

  type Row = { id: string; desc: string; rob: string; model: string; right: boolean }
  const rows: Row[] = []
  for (const a of apps ?? []) {
    const id = a.provider_id as string
    if (isHoldout(id)) continue
    const r = rob.get(id)
    const m = cache.results[id]?.classification?.relevance
    const desc = String((a.raw as { description?: string }).description ?? '').trim()
    // A description too long to quote teaches nothing a shorter one does not.
    if (!r || !m || r === 'skipped' || desc.length < 20 || desc.length > 190) continue
    if (heldOutText.has(canonical(desc))) continue   // a duplicate of a held-out scheme
    rows.push({ id, desc, rob: r, model: m, right: r === m })
  }

  const take = (verdict: string, right: boolean, n: number) =>
    rows.filter((x) => x.rob === verdict && x.right === right).slice(0, n)

  const chosen = [
    ...take('high', true, 4),   // reinforce
    ...take('high', false, 3),  // correct an under-call
    ...take('low', true, 4),    // reinforce
    ...take('low', false, 3),   // correct an over-call
  ]

  console.log(`// Generated by scripts/build-relevance-examples.ts from the expert's own`)
  console.log(`// verdicts, tuning split only. Decisions, not explanations.`)
  console.log(`const RELEVANCE_EXAMPLES = [`)
  for (const c of chosen) {
    const desc = c.desc.replace(/\s+/g, ' ').replace(/'/g, "\\'")
    console.log(`  '${desc} -> ${c.rob}',`)
  }
  console.log(`].join(' | ')`)
  console.error(`\nchose ${chosen.length}: ${chosen.filter(c=>c.rob==='high').length} high, ${chosen.filter(c=>c.rob==='low').length} low; ${chosen.filter(c=>!c.right).length} the model currently gets wrong`)
}
main()
