/**
 * Pick worked examples for the relevance prompt from the expert's own decisions.
 *
 * Decisions, not explanations. Rebuilding the rubric from his written reasons was measured
 * and lost to the rubric inferred from his verdicts: what someone says their rule is and what
 * their decisions encode are not the same thing. So these examples carry a description and a
 * verdict, and no rationale.
 *
 * TUNING SPLIT ONLY. An example drawn from the held-out third would put the answer to a test
 * record directly into the prompt, and that set is the only evidence any of this generalises.
 *
 * Balanced on purpose: examples only from records the model gets wrong would teach it that
 * its instinct is always inverted. Half reinforce what it already does, half correct it.
 *
 * Run from apps/web:  npx tsx scripts/build-relevance-examples.ts
 */
import { loadEnvConfig } from '@next/env'
import { createClient } from '@supabase/supabase-js'
import { createHash } from 'crypto'
import { readFileSync } from 'fs'

loadEnvConfig(process.cwd())
const isHoldout = (id: string) =>
  createHash('sha256').update(`holdout:${id}`).digest().readUInt32BE(0) / 0xffffffff < 1 / 3

async function main() {
  const cachePath = process.argv[2] ?? 'runs/fl-ops.json'
  const db = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.SUPABASE_SERVICE_ROLE_KEY!, {
    auth: { autoRefreshToken: false, persistSession: false },
  })
  const { data: apps } = await db.from('planning_applications')
    .select('provider_id,raw').eq('intelligence_tier', true).order('provider_id')
  const { data: lab } = await db.from('planning_label_submissions')
    .select('record_id,relevance,submitted_at').eq('labeller', 'rob').order('submitted_at')
  const rob = new Map<string, string>()
  for (const l of lab ?? []) rob.set(String(l.record_id), String(l.relevance))
  const cache = JSON.parse(readFileSync(cachePath, 'utf8'))

  type Row = { id: string; desc: string; rob: string; model: string; right: boolean }
  const rows: Row[] = []
  for (const a of apps ?? []) {
    const id = a.provider_id as string
    if (isHoldout(id)) continue
    const r = rob.get(id)
    const m = cache.results[id]?.classification?.relevance
    const desc = String((a.raw as { description?: string }).description ?? '').trim()
    // A description too long to quote teaches nothing a shorter one does not.
    if (!r || !m || r === 'skipped' || desc.length < 20 || desc.length > 190) continue
    rows.push({ id, desc, rob: r, model: m, right: r === m })
  }

  const take = (verdict: string, right: boolean, n: number) =>
    rows.filter((x) => x.rob === verdict && x.right === right).slice(0, n)

  const chosen = [
    ...take('high', true, 4),   // reinforce
    ...take('high', false, 3),  // correct an under-call
    ...take('low', true, 4),    // reinforce
    ...take('low', false, 3),   // correct an over-call
  ]

  console.log(`// Generated by scripts/build-relevance-examples.ts from the expert's own`)
  console.log(`// verdicts, tuning split only. Decisions, not explanations.`)
  console.log(`const RELEVANCE_EXAMPLES = [`)
  for (const c of chosen) {
    const desc = c.desc.replace(/\s+/g, ' ').replace(/'/g, "\\'")
    console.log(`  '${desc} -> ${c.rob}',`)
  }
  console.log(`].join(' | ')`)
  console.error(`\nchose ${chosen.length}: ${chosen.filter(c=>c.rob==='high').length} high, ${chosen.filter(c=>c.rob==='low').length} low; ${chosen.filter(c=>!c.right).length} the model currently gets wrong`)
}
main()
