import fs from 'fs'
import path from 'path'
import {
  storeAddrParts,
  storeTokens,
  units,
  numbers,
  houseNumbers,
  type StoreAddress,
} from '../normalise'

/**
 * The Python matcher (scripts/epc/matchlib.py) runs quarterly over the whole estate;
 * the TypeScript port runs per store as they are imported. If they disagree, the same
 * shop gets a different answer depending on which reached it first, and the symptom is
 * a floor area quietly changing after a quarterly run.
 *
 * Both fixtures are generated BY the Python, so it is the reference implementation and
 * this is a conformance test, not two implementations agreeing with each other.
 * Regenerate with `python3 scripts/epc/dump_normalise_fixture.py`.
 */

interface Fixture {
  input: StoreAddress
  parts: string[]
  tokens: string[]
  units: string[]
  numbers: string[]
  houseNumbers: string[]
}

const FIXTURES = path.join(__dirname, 'fixtures')

function actual(s: StoreAddress) {
  const parts = storeAddrParts(s)
  return {
    parts,
    tokens: storeTokens(s),
    units: [...units(...parts)].sort(),
    numbers: [...numbers(...parts)].sort(),
    houseNumbers: [...houseNumbers(...parts)].sort(),
  }
}

function expectedOf(f: Fixture) {
  return {
    parts: f.parts,
    tokens: f.tokens,
    units: f.units,
    numbers: f.numbers,
    houseNumbers: f.houseNumbers,
  }
}

describe('EPC address normalisation matches matchlib.py', () => {
  const cases: Fixture[] = JSON.parse(
    fs.readFileSync(path.join(FIXTURES, 'normalise-cases.json'), 'utf8')
  )

  it.each(cases.map((c, i) => [i, c.input.address_line_1 || '(empty)', c] as const))(
    'case %i: %s',
    (_i, _label, c) => {
      expect(actual(c.input)).toEqual(expectedOf(c))
    }
  )

  // A digit that is part of a name must never be read as a house number. This is the
  // one that shipped a 9,672 m2 retail park as a McDonald's, so it gets its own test
  // rather than sitting anonymously in the table above.
  it('does not read a name digit as a house number', () => {
    expect([...houseNumbers('JUNCTION 1 RETAIL PARK')]).toEqual([])
    expect([...houseNumbers('UNIT 3, JUNCTION 1 RETAIL PARK')]).toEqual(['3'])
  })

  // numbers() is liberal (it rejects candidates) and houseNumbers() is strict (it
  // accepts them). Collapsing them would be an easy and invisible mistake.
  it('keeps numbers liberal and houseNumbers strict', () => {
    expect([...numbers('JUNCTION 1 RETAIL PARK')]).toEqual(['1'])
    expect([...houseNumbers('JUNCTION 1 RETAIL PARK')]).toEqual([])
  })
})

/**
 * The real adversary: every address in the estate. Gitignored, because it is the
 * product's own address data. Absent locally, this is skipped with a message rather
 * than silently passing — a conformance test that quietly tests nothing is worse than
 * no test.
 */
const estatePath = path.join(FIXTURES, 'normalise-estate.json')
const hasEstate = fs.existsSync(estatePath)

;(hasEstate ? describe : describe.skip)('across the whole store estate', () => {
  it('is byte-identical to matchlib.py for every store', () => {
    const rows: Fixture[] = JSON.parse(fs.readFileSync(estatePath, 'utf8'))
    expect(rows.length).toBeGreaterThan(1000)

    const mismatches: { input: StoreAddress; expected: unknown; actual: unknown }[] = []
    for (const r of rows) {
      const got = actual(r.input)
      const want = expectedOf(r)
      if (JSON.stringify(got) !== JSON.stringify(want)) {
        mismatches.push({ input: r.input, expected: want, actual: got })
        if (mismatches.length >= 5) break
      }
    }

    if (mismatches.length > 0) {
      throw new Error(
        `${mismatches.length}+ of ${rows.length} store addresses normalise differently ` +
          `to matchlib.py. First failures:\n${JSON.stringify(mismatches, null, 2)}`
      )
    }
  })
})

if (!hasEstate) {
  // eslint-disable-next-line no-console
  console.warn(
    '[normalise.test] estate fixture absent — run scripts/epc/dump_normalise_fixture.py ' +
      'to check all 43,070 addresses, not just the 29 curated ones.'
  )
}
