"""Ground truth for the TypeScript normaliser, generated by the Python one.

Writes two fixtures:

  normalise-cases.json   committed. Synthetic addresses chosen to exercise every
                         documented trap in matchlib. Small, readable, and safe to
                         commit because none of it is real store data.

  normalise-estate.json  gitignored. Every real store address in the estate. This is
                         the test that actually matters — 43,070 addresses is a far
                         better adversary than anything anyone would think to write by
                         hand — but it is the product's own address data and does not
                         belong in git. Regenerate with this script; the Jest test skips
                         it when absent and runs it when present.

Run from scripts/epc after dump_all.py.
"""
import csv, json, os
from matchlib import store_addr_parts, store_tokens, units, numbers, house_numbers

OUT = "../../apps/web/src/lib/epc/__tests__/fixtures"

def expected(s):
    parts = store_addr_parts(s)
    return {
        "parts":         parts,
        "tokens":        store_tokens(s),
        "units":         sorted(units(*parts)),
        "numbers":       sorted(numbers(*parts)),
        "houseNumbers":  sorted(house_numbers(*parts)),
    }

def case(a1, a2=None, town=None, county=None):
    s = {"address_line_1": a1, "address_line_2": a2, "town": town, "county": county}
    return {"input": s, **expected(s)}

# Each of these exists because matchlib's docstrings or the assessment name it as a
# way the matching goes wrong.
CASES = [
    # A digit inside a proper name is not a house number. Treating it as one matched a
    # McDonald's to a 9,672 m2 retail park anchor.
    case("Junction 1 Retail Park"),
    case("Unit 3, Junction 1 Retail Park", town="Rugby"),
    # address_line_1 sometimes carries town and postcode inline; the postcode is stripped.
    case("308 Baker Street, Enfield, EN1 3LD", town="Enfield"),
    case("12 High Street SW1A 1AA"),
    # Unit forms.
    case("Unit 4, The Mall"),
    case("Units 4/5 Kings Walk"),
    case("UNIT 12A, Riverside"),
    case("U 7 Trade Park"),
    case("Unit A, The Courtyard"),
    # Ranges, and the 200 cap that stops "1-9999" exploding.
    case("12-14 High Street"),
    case("100 - 104 Queens Road"),
    case("1-9999 Nonsense Way"),
    # Prefixed numbers.
    case("No. 7 The Parade"),
    case("Nos 22-24 Market Square"),
    case("Block 3, Suite 12, Business Centre"),
    case("Plot 9, Industrial Estate"),
    # Ampersand and apostrophe handling, and suffix folding.
    case("Marks & Spencer, 1 Broad Street"),
    case("St John's Road"),
    case("Great North Road"),
    case("The Centre, Center Parade"),
    # Town and county are dropped from tokens as non-evidence.
    case("45 Castle Street", town="Castle", county="Kent"),
    # Everything dropped -> falls back to the undropped tokens rather than nothing.
    case("Retail Park", town="Retail", county="Park"),
    # Noise words only.
    case("The Unit, Ground Floor"),
    # Two lines.
    case("Unit 6", "Westgate Shopping Centre", town="Canterbury", county="Kent"),
    # Degenerate input.
    case(""),
    case(None, "Second line only"),
    case("   "),
    case("%%%"),
    case("123456789 Long Number Road"),
]

os.makedirs(OUT, exist_ok=True)
with open(f"{OUT}/normalise-cases.json", "w") as f:
    json.dump(CASES, f, indent=2)
print(f"wrote {len(CASES)} curated cases")

if os.path.exists("all_stores.csv"):
    rows = []
    for s in csv.DictReader(open("all_stores.csv")):
        rows.append({
            "input": {k: (s.get(k) or None) for k in
                      ("address_line_1", "address_line_2", "town", "county")},
            **expected(s),
        })
    with open(f"{OUT}/normalise-estate.json", "w") as f:
        json.dump(rows, f, separators=(",", ":"))
    print(f"wrote {len(rows):,} estate cases")
else:
    print("all_stores.csv absent — run dump_all.py for the estate fixture")
